print("This is GitHub Tutorial")
print("second commit")
print("This is the file for master")
print("Preping for merging by ort")
print("preping to merge after conflict")
print("changes in master")
print("change in feature")
print("preping for push")
print("changes in master")
print("change in master for new push")